#!/bin/sh
# Drive scripts/screenshots.mjs in a sandbox, where three things get in the way.
#
#  1. Playwright is deliberately not a project dependency, and a copy installed
#     from npm pins a Chromium revision that probably is not the one on the box
#     ("Executable doesn't exist at …/chromium_headless_shell-1243/…"). Rather
#     than hunting the matching Playwright version, this points whatever
#     version is available at whatever browser is actually installed, through a
#     tiny shim that PLAYWRIGHT_MODULE accepts.
#  2. The headless browser has no proxy trust, so the page cannot fetch the
#     catalog from raw.githubusercontent.com and the run hangs waiting for
#     [data-testid=catalog-ready]. Node can fetch it, so fetch it once here and
#     hand the build a local copy.
#  3. node_modules may be missing entirely in a fresh checkout.
#
# Every argument is passed straight through:
#   sh .agents/skills/debug/scripts/shots.sh --scenario client --platform linux
#   sh .agents/skills/debug/scripts/shots.sh --viewport phone --theme dark
# Output lands in screenshots/<scenario>/<viewport>-<theme>/ (gitignored) —
# open the PNGs, do not just trust the exit code.

set -e
root=$(CDPATH= cd -- "$(dirname -- "$0")/../../../.." && pwd)
cache=${NQUAKE_DEBUG_CACHE:-${TMPDIR:-/tmp}/nquake-debug}
mkdir -p "$cache"
cd "$root"

[ -d node_modules ] || npm ci

# 1. A browser Playwright will actually accept.
browser=${PLAYWRIGHT_CHROMIUM:-}
if [ -z "$browser" ]; then
  for c in /opt/pw-browsers/chromium "$HOME/.cache/ms-playwright/chromium"; do
    [ -x "$c" ] && browser=$c && break
  done
fi
if [ -z "$PLAYWRIGHT_MODULE" ] && ! node -e "require.resolve('playwright')" 2>/dev/null; then
  if [ ! -d "$cache/pw/node_modules/playwright" ]; then
    echo "installing playwright into $cache/pw (not a project dependency)" >&2
    mkdir -p "$cache/pw"
    (cd "$cache/pw" && npm init -y >/dev/null 2>&1 && npm i playwright >/dev/null)
  fi
  PLAYWRIGHT_MODULE=$cache/pw/node_modules/playwright
fi
if [ -n "$browser" ]; then
  real=${PLAYWRIGHT_MODULE:-playwright}
  cat > "$cache/pw-shim.mjs" <<EOF
// Generated by shots.sh: real Playwright, but always launching the browser
// that exists on this machine instead of the revision this copy pins.
import pw from "$real";
export const chromium = {
  ...pw.chromium,
  launch: (opts = {}) =>
    pw.chromium.launch({ executablePath: "$browser", ...opts }),
};
export default { ...pw, chromium };
EOF
  PLAYWRIGHT_MODULE=$cache/pw-shim.mjs
  echo "browser: $browser" >&2
fi
export PLAYWRIGHT_MODULE

# 2. A catalog the page can read without leaving the machine.
case " $* " in
  *" --manifest "*) ;;
  *)
    if [ ! -s "$cache/manifest.json" ]; then
      echo "fetching the distfiles manifest for the offline browser" >&2
      curl -fsS -o "$cache/manifest.json" \
        https://raw.githubusercontent.com/nQuake/distfiles/master/manifest.json
    fi
    set -- "$@" --manifest "$cache/manifest.json"
    ;;
esac

exec node scripts/screenshots.mjs "$@"
