// Text files the installer writes itself: the ezQuake preset, the server
// port / password / QTV / QWFWD configs, and the start/stop scripts. Pure
// string builders — the plan decides *where* they go.

import type { ClientConfig, ServerOptions } from "./options.ts";
import { FIXUP_SCRIPT } from "./paths.ts";
import type { Platform } from "./platform.ts";

const CRLF = "\r\n";

function lines(platform: Platform, rows: string[]): string {
  const eol = platform === "windows" ? CRLF : "\n";
  return rows.join(eol) + eol;
}

function quote(s: string): string {
  return `"${s.replace(/"/g, "'")}"`;
}

// ---------------------------------------------------------------- client

/** A script the installer generates, and whether it needs the executable bit. */
export interface ScriptFile {
  path: string;
  text: string;
  executable: boolean;
}

/**
 * `ezquake/configs/preset.cfg`, which nQuake's autoexec loads on first run —
 * after `nquake_default.cfg`, so anything set here wins over nQuake's defaults.
 *
 * That ordering is what lets this file fix `cl_fakename`. ezQuake rewrites
 * every `say_team` message as `<cl_fakename><cl_fakename_suffix><message>`
 * (`cl_cmd.c`, `CL_Say_f`) and ships the cvar empty, i.e. off — but
 * `nquake_default.cfg` sets it to `"pla"`, a leftover placeholder from
 * "player". So on a stock nQuake every team message comes out as
 * "PLA: ...", whatever the player calls themselves, and `name`, `nick`,
 * `tname` and `tpname` all fail to change it because none of them feed
 * `cl_fakename`. Since the nickname is the one thing the installer asks for,
 * it sets both, and says so in the file.
 */
export function renderPresetCfg(cfg: ClientConfig, platform: Platform): string {
  const k = cfg.keys;
  const nick = cfg.name.trim() || "Player";
  return lines(platform, [
    "// This config was generated by the nQuake web installer",
    "",
    `name ${quote(nick)}`,
    "",
    "// Team messages (say_team) are prefixed with cl_fakename, not with your",
    '// name. nQuake\'s default config sets it to "pla", which is why team',
    '// chat reads "PLA: ..." until this line overrides it. Clear it with',
    '// cl_fakename "" to send team messages under your real name.',
    `cl_fakename ${quote(nick)}`,
    "",
    cfg.invertMouse ? 'm_pitch "-0.022" // invert mouse' : 'm_pitch "0.022"',
    "",
    `bind ${k.forward} "+forward"`,
    `bind ${k.back} "+back"`,
    `bind ${k.left} "+moveleft"`,
    `bind ${k.right} "+moveright"`,
    `bind ${k.jump} "+jump"`,
  ]);
}

/**
 * `start_ezquake.sh`: the client launcher for Linux and macOS.
 *
 * A browser cannot set the executable bit, so a freshly installed AppImage or
 * `.app` will not start — the whole reason this script exists. It chmods
 * itself and the client first, then launches, which makes `sh start_ezquake.sh`
 * enough the very first time and `./start_ezquake.sh` enough afterwards. The
 * desktop app sets the bits itself, so there it works straight away.
 * Windows needs none of this and gets no script.
 */
export function renderClientLaunchScript(
  platform: Platform,
): ScriptFile | null {
  if (platform === "windows") return null;
  const text =
    platform === "macos"
      ? lines(platform, [
          "#!/bin/sh",
          "# Generated by the nQuake web installer: starts ezQuake.",
          "# Browsers cannot set the executable bit or clear the quarantine",
          "# flag macOS puts on a download, so this script does both first.",
          'cd "$(dirname "$0")" || exit 1',
          "if [ ! -d ezQuake.app ]; then",
          '  echo "ezQuake.app is not in this folder. Get it from https://ezquake.com/"',
          "  exit 1",
          "fi",
          'chmod +x "$0" ezQuake.app/Contents/MacOS/* 2>/dev/null',
          "xattr -dr com.apple.quarantine ezQuake.app 2>/dev/null",
          'exec open ezQuake.app --args "$@"',
        ])
      : lines(platform, [
          "#!/bin/sh",
          "# Generated by the nQuake web installer: starts ezQuake.",
          "# Browsers cannot set the executable bit, so this script does it first.",
          'cd "$(dirname "$0")" || exit 1',
          "APP=./ezQuake-x86_64.AppImage",
          '[ -f "$APP" ] || APP=$(ls -1 ./*.AppImage 2>/dev/null | head -n 1)',
          'if [ -z "$APP" ] || [ ! -f "$APP" ]; then',
          '  echo "No ezQuake AppImage in this folder. Get one from https://ezquake.com/"',
          "  exit 1",
          "fi",
          'chmod +x "$0" "$APP" 2>/dev/null',
          'exec "$APP" "$@"',
        ]);
  return { path: "start_ezquake.sh", text, executable: true };
}

// ------------------------------------------------------- the Windows fixup

/** One file waiting under its `.nqinstall` name for its real one. */
export interface SidecarRename {
  from: string;
  to: string;
}

function winPath(path: string): string {
  return path.replace(/\//g, "\\");
}

/**
 * `nquake-finish.bat`: the last step of a browser install on Windows.
 *
 * Chromium will not let a web page create `.cfg` or `.dll` files on Windows
 * (see `domain/paths.ts`), so the installer parks them under a `.nqinstall`
 * suffix and generates this script to move them into place. It is the same
 * trick the `start_*.sh` launchers use for the executable bit a browser
 * cannot set — something outside the browser does the one thing the browser
 * is not allowed to do, on the first run.
 *
 * Idempotent (every step is guarded by `if exist`), so running it twice, or
 * after a second install into the same folder, is harmless. `/quiet` skips
 * the closing message so `start_servers.bat` can call it.
 */
export function renderFixupScript(
  renames: SidecarRename[],
  /** An existing `config.cfg` to move aside first, as an update install does. */
  backup: { path: string; to: string } | null = null,
): ScriptFile {
  const rows = [
    "@echo off",
    "rem Generated by the nQuake web installer: the last step of the install.",
    "rem",
    "rem Chrome and Edge are not allowed to create .cfg or .dll files on",
    "rem Windows, so the installer wrote them next to their real names with a",
    "rem .nqinstall suffix. This script puts them back. Run it once, then",
    "rem delete it.",
    "setlocal",
    'cd /d "%~dp0"',
  ];
  if (backup) {
    rows.push(
      `if exist "${winPath(backup.path)}" ren "${winPath(backup.path)}" "${backup.to}"`,
    );
  }
  for (const r of renames) {
    rows.push(
      `if exist "${winPath(r.from)}" move /y "${winPath(r.from)}" "${winPath(r.to)}" >nul`,
    );
  }
  rows.push(
    'if /i "%~1"=="/quiet" exit /b 0',
    "echo.",
    `echo ${renames.length} file(s) put in place. nQuake is ready.`,
    "echo You can delete this file now.",
    "pause",
  );
  return {
    path: FIXUP_SCRIPT,
    text: lines("windows", rows),
    executable: false,
  };
}

// ---------------------------------------------------------------- server

/** A game server the plan sets up: one MVDSV process. */
export interface GameServer {
  /** Short id used in script and config names, e.g. `ktx1`, `ffa`. */
  id: string;
  label: string;
  port: number;
  /** MVDSV `-game` directory. */
  game: string;
  /** Config passed as `+exec`. */
  cfg: string;
}

export function adminInfo(o: ServerOptions): string {
  const name = o.adminName.trim() || "admin";
  const email = o.adminEmail.trim();
  return email ? `${name} <${email}>` : name;
}

/** Replace the `NQUAKESV_*` placeholders the addon configs carry. */
export function applyPlaceholders(
  text: string,
  vars: Record<string, string>,
): string {
  let out = text;
  for (const [key, value] of Object.entries(vars)) {
    out = out.split(key).join(value);
  }
  return out;
}

export function serverPlaceholders(
  o: ServerOptions,
  port: number,
): Record<string, string> {
  return {
    NQUAKESV_HOSTNAME: o.hostname.trim() || "nQuake KTX Server",
    NQUAKESV_ADMIN: adminInfo(o),
    NQUAKESV_IP: o.listenAddress.trim(),
    NQUAKESV_PORT: String(port),
  };
}

/**
 * `ktx/portN.cfg`: the distfiles `port_template.cfg` (motd, modes) with the
 * generated server info appended — what `update_configs.sh` did on Linux.
 */
export function renderKtxPortCfg(
  template: string,
  o: ServerOptions,
  port: number,
  platform: Platform,
): string {
  const hostname = o.hostname.trim() || "nQuake KTX Server";
  const body = template.replace(/\r?\n/g, "\n").trimEnd();
  const generated = [
    "",
    "// generated by the nQuake web installer",
    `hostname ${quote(`${hostname}:${port}`)}`,
    `sv_admininfo ${quote(adminInfo(o))}`,
    ...(o.listenAddress.trim()
      ? [`sv_serverip ${quote(o.listenAddress.trim())}`]
      : []),
    `qtv_streamport ${quote(String(port))}`,
    `set k_motd1 ${quote(hostname)}`,
    ...(o.listenAddress.trim()
      ? [`set hostport ${quote(`${o.listenAddress.trim()}:${port}`)}`]
      : []),
  ];
  const eol = platform === "windows" ? CRLF : "\n";
  return (body + "\n" + generated.join("\n") + "\n").replace(/\n/g, eol);
}

/** `ktx/pwd.cfg`: rcon and QTV passwords, exec'd by server.cfg. */
export function renderPwdCfg(o: ServerOptions, platform: Platform): string {
  return lines(platform, [
    "// generated by the nQuake web installer",
    `rcon_password ${quote(o.rconPassword)}`,
    `qtv_password ${quote("")}`,
  ]);
}

/** `qtv/qtv.cfg`: the distfiles template plus this install's servers. */
export function renderQtvCfg(
  template: string,
  o: ServerOptions,
  servers: GameServer[],
  platform: Platform,
): string {
  const hostname = o.hostname.trim() || "nQuake KTX Server";
  const body = template.replace(/\r?\n/g, "\n").trimEnd();
  const address = o.listenAddress.trim()
    ? `${o.listenAddress.trim()}:${o.qtvPort}`
    : String(o.qtvPort);
  const generated = [
    "",
    "// generated by the nQuake web installer",
    `hostname ${quote(`${hostname} QTV`)}`,
    `admin_password ${quote(o.qtvPassword)}`,
    `mvdport ${o.qtvPort}`,
    `address ${address}`,
    ...servers.map((s) => `qtv 127.0.0.1:${s.port}`),
  ];
  const eol = platform === "windows" ? CRLF : "\n";
  return (body + "\n" + generated.join("\n") + "\n").replace(/\n/g, eol);
}

/** `qwfwd/qwfwd.cfg`. */
export function renderQwfwdCfg(o: ServerOptions, platform: Platform): string {
  const hostname = o.hostname.trim() || "nQuake KTX Server";
  return lines(platform, [
    "// generated by the nQuake web installer",
    `set hostname ${quote(`${hostname} QWFWD`)}`,
    `set net_port ${o.qwfwdPort}`,
  ]);
}

/** Start/stop scripts for every process this install runs. */
export function renderStartScripts(
  platform: Platform,
  o: ServerOptions,
  servers: GameServer[],
): ScriptFile[] {
  if (platform === "windows") {
    const start: string[] = [
      "@echo off",
      "rem Generated by the nQuake web installer: starts every server in its own window.",
      "cd /d %~dp0",
      // A browser install on Windows cannot name the KTX .dll or any .cfg;
      // the fixup script it leaves behind puts them in place. Harmless when
      // it isn't there (the desktop app and every other surface).
      `if exist "%~dp0${FIXUP_SCRIPT}" call "%~dp0${FIXUP_SCRIPT}" /quiet`,
    ];
    for (const s of servers) {
      start.push(
        `start "${s.label} (${s.port})" mvdsv.exe -port ${s.port} -game ${s.game} +exec ${s.cfg}`,
      );
    }
    if (o.qtv) start.push(`start "QTV" /d qtv qtv.exe +exec qtv.cfg`);
    if (o.qwfwd) start.push(`start "QWFWD" /d qwfwd qwfwd.exe`);
    const stop = [
      "@echo off",
      "rem Generated by the nQuake web installer: stops every server started by start_servers.bat.",
      "taskkill /im mvdsv.exe /f",
      ...(o.qtv ? ["taskkill /im qtv.exe /f"] : []),
      ...(o.qwfwd ? ["taskkill /im qwfwd.exe /f"] : []),
    ];
    const perPort: ScriptFile[] = servers.map((s) => ({
      path: `start_${s.id}_${s.port}.bat`,
      text: lines(platform, [
        "@echo off",
        "cd /d %~dp0",
        `mvdsv.exe -port ${s.port} -game ${s.game} +exec ${s.cfg}`,
      ]),
      executable: false,
    }));
    return [
      {
        path: "start_servers.bat",
        text: lines(platform, start),
        executable: false,
      },
      {
        path: "stop_servers.bat",
        text: lines(platform, stop),
        executable: false,
      },
      ...perPort,
    ];
  }

  // Linux / macOS: one restart-loop runner per process (the shape of the
  // `run/*.sh` scripts nQuakesv generated), plus start/stop wrappers.
  const runners: ScriptFile[] = servers.map((s) => ({
    path: `run/${s.id}_${s.port}.sh`,
    text: lines(platform, [
      "#!/bin/sh",
      `# Generated by the nQuake web installer: ${s.label} on port ${s.port}.`,
      'cd "$(dirname "$0")/.." || exit 1',
      "while true; do",
      `  ./mvdsv -port ${s.port} -game ${s.game} +exec ${s.cfg}`,
      "  sleep 5",
      "done",
    ]),
    executable: true,
  }));
  if (o.qtv) {
    runners.push({
      path: "run/qtv.sh",
      text: lines(platform, [
        "#!/bin/sh",
        "# Generated by the nQuake web installer: QTV.",
        'cd "$(dirname "$0")/../qtv" || exit 1',
        "while true; do",
        "  ./qtv.bin +exec qtv.cfg",
        "  sleep 5",
        "done",
      ]),
      executable: true,
    });
  }
  if (o.qwfwd) {
    runners.push({
      path: "run/qwfwd.sh",
      text: lines(platform, [
        "#!/bin/sh",
        "# Generated by the nQuake web installer: QWFWD proxy.",
        'cd "$(dirname "$0")/../qwfwd" || exit 1',
        "while true; do",
        "  ./qwfwd.bin",
        "  sleep 5",
        "done",
      ]),
      executable: true,
    });
  }
  const binaries = [
    "mvdsv",
    "ktx/mvdfinish.qws",
    ...(o.qtv ? ["qtv/qtv.bin"] : []),
    ...(o.qwfwd ? ["qwfwd/qwfwd.bin"] : []),
  ];
  const start = [
    "#!/bin/sh",
    "# Generated by the nQuake web installer: starts every server in the background.",
    "# Browsers cannot set the executable bit, so this script does it first.",
    'cd "$(dirname "$0")" || exit 1',
    `chmod +x ${binaries.join(" ")} run/*.sh start_servers.sh stop_servers.sh 2>/dev/null`,
    "mkdir -p logs",
    ...runners.map((r) => {
      const name = r.path.replace(/^run\//, "").replace(/\.sh$/, "");
      return `pgrep -f "${r.path}" >/dev/null || nohup ./${r.path} >logs/${name}.log 2>&1 &`;
    }),
    'echo "Servers started. Logs are in ./logs/. Stop them with ./stop_servers.sh."',
  ];
  const stop = [
    "#!/bin/sh",
    "# Generated by the nQuake web installer: stops the run loops and the servers.",
    ...runners.map((r) => `pkill -f "${r.path}" 2>/dev/null`),
    "pkill -x mvdsv 2>/dev/null",
    ...(o.qtv ? ["pkill -x qtv.bin 2>/dev/null"] : []),
    ...(o.qwfwd ? ["pkill -x qwfwd.bin 2>/dev/null"] : []),
    'echo "Servers stopped."',
  ];
  return [
    {
      path: "start_servers.sh",
      text: lines(platform, start),
      executable: true,
    },
    { path: "stop_servers.sh", text: lines(platform, stop), executable: true },
    ...runners,
  ];
}
